name: Metrics
on:
  # Updates every day at 16:00 UTC (01:00 KST)
  schedule: [{cron: "0 16 * * *"}]
  workflow_dispatch:
  push:
    branches: ["main"]
jobs:
  metrics-main:
    runs-on: ubuntu-latest
    steps:
      # See action.yml for all options
      - uses: lowlighter/metrics@v3.34
        with:
          # Your GitHub token
          token: ${{ secrets.METRICS_TOKEN }}

          user: ggyuchive
          base: header, activity, community, repositories, metadata
          filename: metrics-main.svg
          template: classic
          repositories: 200
          repositories_batch: 50
          base_indepth: yes
          base_hireable: yes

  metrics-lang-notable:
    runs-on: ubuntu-latest
    steps:
      # See action.yml for all options
      - uses: lowlighter/metrics@v3.34
        with:
          # Your GitHub token
          token: ${{ secrets.METRICS_TOKEN }}

          plugin_languages: yes
          plugin_languages_ignored: CMake, HTML, CSS, QML, QMake, NSIS, Makefile, PowerShell, NASL
          plugin_languages_sections: most-used
          plugin_languages_limit: 8
          plugin_languages_details: percentage
          plugin_languages_indepth: no
          plugin_languages_analysis_timeout: 30
          plugin_languages_categories: programming

          plugin_notable: yes
          plugin_notable_filter: stars:>10
          plugin_notable_repositories: yes
          plugin_notable_indepth: no

          user: ggyuchive
          base: ''
          filename: metrics-lang-notable.svg
          template: classic
          repositories: 200
          repositories_batch: 50